# Generated by Django 4.0.3 on 2022-03-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_testtrain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtrain',
            options={'ordering': ['id'], 'verbose_name': 'ТЕСТПоезд', 'verbose_name_plural': 'ТЕСТПоезда'},
        ),
    ]
