# Generated by Django 4.0.3 on 2022-03-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_ulicia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='ulicia',
            options={'ordering': ['name'], 'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
    ]
